### ISSUE TITLE
申请加入Egg.js Community

### ISSUE THREAD

**Issue by pandaTerminator** [eggjs-community/README#11]
* **贡献**: 暂无，(ps: 公司内部分享egg，新的项目已经由egg搭建开发。自己的网站后端API服务也改成了egg框架 [back-end](https://github.com/pandasjw/back-end))
* **动机**: 花了2个周末的时间，挑选了一个适合于公司敏捷开发的node framework。觉得egg很适合，框架本身非常的用心，希望自己能够成为参与者和贡献者。

**Comment by duncup** [comment]
已通过，不好意思久等了。
