### ISSUE TITLE
申请加入Egg.js Community

### ISSUE THREAD

**Issue by fairyly** [eggjs-community/README#12]
贡献:

暂时还没, 平时也在总结一些 Node 的技术 [myNode](https://github.com/fairyly/mynodejs/tree/gh-pages)
和一些热门技术,
希望写写 egg 的脚手架

动机:
希望通过下班时间多学习,深入了解 Node，希望 egg 发展得更好。

想开发一些关于 egg 的脚手架或者应用生成器。比如 egg-generator 或者 koa-generator 这样的。

热爱技术,支持开源技术！

**Comment by duncup** [comment]
已通过，不好意思久等了。
