### ISSUE TITLE
申请加入Egg.js Community

### ISSUE THREAD

**Issue by callmez** [eggjs-community/README#15]
* **贡献**:
https://github.com/callmez/egg-cache-manager 基于catbox.js的缓存组件, 加入了tag标记过期特点
https://github.com/callmez/egg-task 基于bull.js, 封装完善的任务队列组件
https://github.com/callmez/egg-generator CURD生成器
* **动机**:
想深入了解eggjs运行机制, 构建更贴合的eggjs插件. 后续插件版本提供typescript的版本寻求最佳实践

**Comment by duncup** [comment]
已通过，不好意思久等了。
