### ISSUE TITLE
申请加入Egg.js Community

### ISSUE THREAD

**Issue by reezon** [eggjs-community/README#3]
* **贡献**:
 - [egg-beecloud-pay](https://github.com/reezon/egg-beecloud-pay)
 - [egg-jpush](https://github.com/reezon/egg-jpush)
 - [egg-zmxy](https://github.com/reezon/egg-zmxy)
 - [egg-netease-cloud-music](https://github.com/reezon/egg-netease-cloud-music)

* **动机**:
喜欢egg，目前公司的后端架构正逐步往egg重构，希望自己能够为这个社区贡献一份力量

**Comment by thonatos** [comment]
欢迎，也欢迎推送项目到 Org.

**Comment by fengmk2** [comment]
@atian25 谁来审核通过？

**Comment by atian25** [comment]
这边是社区的， @thonatos 他们自己运营就好了

**Comment by atian25** [comment]
@fengmk2

**Comment by duncup** [comment]
目前好像就我和 @thonatos 两个人在这玩😂

**Comment by thonatos** [comment]
先收集，后续出个计划好推进呗

**Comment by atian25** [comment]
群里面那么多人，你们组织呗

**Comment by duncup** [comment]
@reezon 看到你已经加入了，先关闭了。
