### ISSUE TITLE
申请加入 Egg.js Community

### ISSUE THREAD

**Issue by MrTreasure** [eggjs-community/README#4]
* **贡献**: 
1.  活跃于[知乎](https://www.zhihu.com/people/treasue/activities) JS开发话题，致力于帮助更多前端从业者、入门者解决问题
2. 在[简书](https://www.jianshu.com/u/6a9e0f0bfa7b)上长期编写前端以及Node方面相关学习型文章
3. 在[github](https://github.com/MrTreasure/ts-koa)上编写 ts-koa，一个以 typescript 编写的，仿照egg.js各个模块实现的 web 服务

* **动机**:
1. 继续深入对Node的学习
2. 尝试使用typescript编写egg的服务
3. 想要加入阿里，从事Node中间件开发

**Comment by thonatos** [comment]
欢迎欢迎，不过，这里是社区哦，加入阿里还是要靠自己努力的！

**Comment by duncup** [comment]
@MrTreasure 邀请已经发出，关闭了。
