### ISSUE TITLE
申请加入Egg.js Community

### ISSUE THREAD

**Issue by fomenyesu** [eggjs-community/README#5]
* **贡献**:

[egg-restapi-module-tool](https://github.com/fomenyesu/egg-restapi-module-tool)

[egg-mongodb-example](https://github.com/fomenyesu/egg-mongodb-example)

* **动机**:

1. 使用 egg 的重度用户，上线了几个项目，希望egg发展得更好。

2. 想开发一些关于egg的扩展应用。比如上面的restapi。

3. 支持开源！

+1 1 tada 1

**Comment by duncup** [comment]
:smile: 欢迎欢迎，稍等邀请邮件就到。

**Comment by fomenyesu** [comment]
thx !!
