### ISSUE TITLE
申请转移项目到该组织

### ISSUE THREAD

**Issue by sinchang** [eggjs-community/README#6]
Hi all.

最近在使用 eggjs 写社区开源项目 [realworld](https://realworld.io/)，现在想申请转移项目 [eggjs-realworld-example-app](https://github.com/sinchang/eggjs-realworld-example-app) 到该组织，方便感兴趣的同学一起参与。

Thanks.

cc @atian25 @thonatos

**Comment by duncup** [comment]
欢迎欢迎，不过先说明下，这边是社区组，不是官方组。邀请等下就到。

**Comment by duncup** [comment]
邀请已发出，先关闭了。
