### ISSUE TITLE
Azard 申请加入

### ISSUE THREAD

**Issue by Azard** [eggjs-community/README#8]
* **贡献**:
https://github.com/Azard/egg-oauth2-server
还有一些文档中译英的工作。

* **动机**:
建设相关生态。

**Comment by duncup** [comment]
@Azard 欢迎，邀请稍等就到。另外确认下，在群里么？看你的 账号有点眼熟。

**Comment by Azard** [comment]
不在，微信群还没拉我

**Comment by duncup** [comment]
先关闭了
