### ISSUE TITLE
egg-mysql bug

### ISSUE THREAD

**Issue by richard1015** [eggjs-community/README#9]
* **贡献**:
* **动机**:

mysql.createInstance 当本地服务器没有mysql服务时，调用该方法直接异常终止服务， 期望 这个方法中 有异常抛出，而不会导致项目直接终止
目前解决方案为  我自己在程序中判断 mysql 端口是否占用，未占用代表，此时服务器未安装mysql 或 未启动服务。
![image](https://user-images.githubusercontent.com/13060263/41826090-72fca44e-7859-11e8-8f66-916fb449de8c.png)

**Comment by atian25** [comment]
https://github.com/eggjs/egg/issues/2716

这里不是讨论过了么

**Comment by richard1015** [comment]
是啊， 所以希望你们  在mysql.createInstance  中加一个抛异常

**Comment by atian25** [comment]
本来就会抛异常，但有个 beforeStart 的检测在，所以你不能在启动期就创建了。
可以在 app/extend 那边做一个 getter 来延迟初始化，或者在 egg-ready 之后再初始化。

**Comment by richard1015** [comment]
ok ,我已经在extend 处理了
